version: '3'

services:

  producer:
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: "${TOPIC_NAME}"
      BATCH_SIZE: ${BATCH_SIZE}
      SLEEP_TIME: ${SLEEP_TIME}
      DATA_DIR_REGEX: "${DATA_DIR_REGEX}"

      2003_EASY_HAM_2_URL: "https://spamassassin.apache.org/old/publiccorpus/20030228_easy_ham_2.tar.bz2"
      2003_HARD_HAM_URL: "https://spamassassin.apache.org/old/publiccorpus/20030228_hard_ham.tar.bz2"
      2003_SPAM_2_URL: "https://spamassassin.apache.org/old/publiccorpus/20030228_spam_2.tar.bz2"
      2005_SPAM_2_URL: "https://spamassassin.apache.org/old/publiccorpus/20050311_spam_2.tar.bz2"

networks:
  default:
    external:
      name: kafka-network
