version: '3'

services:

  producer:
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: "${TOPIC_NAME}"
      BATCH_SIZE: ${BATCH_SIZE}
      SLEEP_TIME: ${SLEEP_TIME}

networks:
  default:
    external:
      name: kafka-network
