version: '3'

services:

  producer:
    build: .
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_NAME: "${TOPIC_NAME}"
      BATCH_SIZE: ${BATCH_SIZE}
      SLEEP_TIME: ${SLEEP_TIME}
      DATA_DIR_REGEX: "${DATA_DIR_REGEX}"
      2003_EASY_HAM_2_URL: "${2003_EASY_HAM_2_URL}"
      2003_HARD_HAM_URL: "${2003_HARD_HAM_URL}"
      2003_SPAM_2_URL: "${2003_SPAM_2_URL}"
      2005_SPAM_2_URL: "${2005_SPAM_2_URL}"

networks:
  default:
    external:
      name: kafka-network
