version: "3"

services:
  datavis:
    container_name: datavis
    hostname: datavis
    build:
      context: .
      args:
        - CONTAINER_HOSTNAME=datavis
    ports:
        - 8888:8888

networks:
  default:
    external:
      name: cassandra-network
