version: "3"

services:

  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1

  broker:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      # Create spotify.topic topic, with 1 partition, 1 replica
      # Create twitter.topic topic, with 1 partition, 1 replica (not used currently)
      KAFKA_CREATE_TOPICS: "${TOPIC_NAME}:1:1,${NEWTWEET_TOPIC_NAME}:1:1,${WEATHER_TOPIC_NAME}:1:1"

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    container_name: kakfa-manager
    restart: always
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: smellycat
    command: -Dpidfile.path=/dev/null

networks:
  default:
    external:
      name: kafka-network
